name: Test CI

on:
  push:
    branches: [ main ]  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches: [ main ]  # Also trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Choose the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest  # Assumes your tests are run with pytest

    # Add additional steps as needed, such as deploying your application
